name: flutter_chatx
description: Flutter version 3.10.5

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  flutter_bloc: ^8.1.3
  get: ^4.6.5
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Images/


