name: flutter_chatx
description: Flutter version 3.10.5

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  flutter_bloc: ^8.1.3
  get: ^4.6.5
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  cloud_firestore: ^4.8.4
  flutter_spinkit: ^5.2.0
  firebase_auth: ^4.7.2
  percent_indicator: ^4.2.3
  open_file: ^3.3.2
  dio: ^5.3.2
  path_provider: ^2.1.0
  image_picker: ^1.0.2
  firebase_storage: ^11.2.6
  path: ^1.8.3
  file_picker: ^5.3.4
  uuid: ^4.0.0
  extended_image: ^8.0.2
  blur: ^3.1.0
  flutter_image_compress: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Images/


