// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC5WqBDQuwmXGe9zrod2y2v3ptWf-Yh94',
    appId: '1:233569956709:android:b01f95ce856b09f887278c',
    messagingSenderId: '233569956709',
    projectId: 'chatx-31159',
    databaseURL: 'https://chatx-31159-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatx-31159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB19xBRRNH7yDDvk4Ljf7RHxL44INKdH4c',
    appId: '1:233569956709:ios:eb2b4b7b3e2d4ff287278c',
    messagingSenderId: '233569956709',
    projectId: 'chatx-31159',
    databaseURL: 'https://chatx-31159-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatx-31159.appspot.com',
    androidClientId: '233569956709-g848c1f5olpnkdomdotk63tv2ngnu940.apps.googleusercontent.com',
    iosClientId: '233569956709-4h3vau5avc3bipb4bvd6aq9itk1joe3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatx',
  );
}
